[package]
name = "language-modeler"
version = "0.1.0"
authors = ["Christopher T Smith <git@chrstsmth.ca>"]

[dependencies]
serde = "*"
serde_json = "*"

[[bin]]
name = "langauge-modeler"
path = "src/language-modeler.rs"
