[package]
name = "dictionary"
version = "0.1.0"
authors = ["Christopher T Smith <git@chrstsmth.ca>"]

[dependencies]
ctrlc = "*"
clap = "*"
cipher-lib = { version = "*", path = "../../cipher-lib" }
common = { version = "*", path = "../common" }

[[bin]]
name = "dictionary"
path = "src/main.rs"
