[package]
name = "cipher-tools-lib"
version = "0.1.0"
authors = ["Christopher T Smith <git@chrstsmth.ca>"]

[dependencies]
cipher-lib = { version = "*", path = "../cipher-lib" }
clap = "*"
serde_json = "*"
