[package]
name = "common"
version = "0.1.0"
authors = ["Christopher T Smith <git@chrstsmth.ca>"]

[dependencies]
clap = "*"
serde = "*"
serde_json = "*"
cipher-lib = { version = "*", path = "../../cipher-lib" }
